stages:
  - build
  - test
  - codereview
  - package

image: maven:3.9.8-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build-job:
  stage: build
  script:
    - echo "ğŸ—ï¸ Building project..."
    - mvn clean compile

test-job:
  stage: test
  script:
    - echo "ğŸ§ª Running tests..."
    - mvn test

codereview-job:
  stage: codereview
  script:
    - echo "ğŸ” Running SonarCloud analysis..."
    - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=	SonarQube-Maven \
        -Dsonar.organization=himanshu0ic7 \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$SONAR_TOKEN
  only:
    - main
    - merge_requests

package-job:
  stage: package
  script:
    - echo "ğŸ“¦ Packaging application..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
